import type { ProviderCatalog } from "./types.js";

export const PROVIDER_CATALOG: ProviderCatalog = {
  // ── Anthropic ──────────────────────────────────────────────────────────

  anthropic: {
    displayName: "Anthropic",
    protocol: "anthropic",
    defaultUrl: "https://api.anthropic.com",
    apiKeyEnvVar: "ANTHROPIC_API_KEY",
    models: {
      "claude-sonnet-4-5-20250929": {
        displayName: "Claude Sonnet 4.5",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 200000,
          maxOutputTokens: 65536,
        },
        multimodal: {
          input: ["text", "image", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["claude-sonnet-4.5", "claude-3-5-sonnet-20250929"],
      },
      "claude-opus-4-20250514": {
        displayName: "Claude Opus 4",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 128_000,
        },
        multimodal: {
          input: ["text", "image", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["claude-opus-4", "claude-opus-4.6"],
      },
      "claude-sonnet-4-20250514": {
        displayName: "Claude Sonnet 4",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 16384,
        },
        multimodal: {
          input: ["text", "image", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["claude-sonnet-4"],
      },
      "claude-sonnet-4.6": {
        displayName: "Claude Sonnet 4.6",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 128000,
        },
        multimodal: {
          input: ["text", "image", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["claude-sonnet-4-6"],
      },
      "claude-opus-4.8-20250613": {
        displayName: "Claude Opus 4.8",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true, // adaptive thinking (4.7+)
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 128_000,
        },
        multimodal: {
          input: ["text", "image", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["claude-opus-4.8"],
      },
      "claude-opus-4.7-20250613": {
        displayName: "Claude Opus 4.7",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true, // adaptive thinking (4.7+)
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 128_000,
        },
        multimodal: {
          input: ["text", "image", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["claude-opus-4.7"],
      },
      "claude-opus-5-20250801": {
        displayName: "Claude Opus 5",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true, // adaptive thinking, always-on
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 128_000,
        },
        multimodal: {
          input: ["text", "image", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["claude-opus-5"],
      },
      "claude-sonnet-5-20250801": {
        displayName: "Claude Sonnet 5",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true, // adaptive thinking, always-on
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 128_000,
        },
        multimodal: {
          input: ["text", "image", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["claude-sonnet-5"],
      },
      "claude-fable-5-20250801": {
        displayName: "Claude Fable 5",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 128_000,
        },
        multimodal: {
          input: ["text", "image", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["claude-fable-5"],
      },
      "claude-mythos-5-20250801": {
        displayName: "Claude Mythos 5",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 128_000,
        },
        multimodal: {
          input: ["text", "image", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["claude-mythos-5"],
      },
      "claude-haiku-3-5-20241022": {
        displayName: "Claude 3.5 Haiku",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 200000,
          maxOutputTokens: 8192,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["claude-3-5-haiku", "claude-3.5-haiku", "claude-haiku-3.5"],
      },
    },
  },

  // ── OpenAI ─────────────────────────────────────────────────────────────

  openai: {
    displayName: "OpenAI",
    protocol: "openai",
    defaultUrl: "https://api.openai.com/v1",
    apiKeyEnvVar: "OPENAI_API_KEY",
    models: {
      "gpt-4o": {
        displayName: "GPT-4o",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 128000,
          maxOutputTokens: 16384,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["gpt-4o-2024-11-20"],
      },
      "gpt-4o-mini": {
        displayName: "GPT-4o Mini",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 128000,
          maxOutputTokens: 16384,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "gpt-4.1": {
        displayName: "GPT-4.1",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_050_000,
          maxOutputTokens: 131_072,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "gpt-4.1-mini": {
        displayName: "GPT-4.1 Mini",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_050_000,
          maxOutputTokens: 131_072,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      o3: {
        displayName: "o3",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 200000,
          maxOutputTokens: 100000,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "o3-mini": {
        displayName: "o3 Mini",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 200000,
          maxOutputTokens: 100000,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "gpt-5.5": {
        displayName: "GPT-5.5",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_050_000,
          maxOutputTokens: 131_072,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "gpt-5.6-sol": {
        displayName: "GPT-5.6 Sol",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_050_000,
          maxOutputTokens: 131_072,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["gpt-5.6"],
      },
      "o4-mini": {
        displayName: "o4 Mini",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 200_000,
          maxOutputTokens: 100_000,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
    },
  },

  // ── OpenAI Responses API ──────────────────────────────────────────────

  "openai-responses": {
    displayName: "OpenAI (Responses API)",
    protocol: "openai-responses",
    defaultUrl: "https://api.openai.com/v1",
    apiKeyEnvVar: "OPENAI_API_KEY",
    models: {
      "gpt-4o": {
        displayName: "GPT-4o",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 128000,
          maxOutputTokens: 16384,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["gpt-4o-2024-11-20"],
      },
      "gpt-4o-mini": {
        displayName: "GPT-4o Mini",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 128000,
          maxOutputTokens: 16384,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "gpt-4.1": {
        displayName: "GPT-4.1",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_050_000,
          maxOutputTokens: 131_072,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "gpt-4.1-mini": {
        displayName: "GPT-4.1 Mini",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_050_000,
          maxOutputTokens: 131_072,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      o3: {
        displayName: "o3",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 200000,
          maxOutputTokens: 100000,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "o3-mini": {
        displayName: "o3 Mini",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 200000,
          maxOutputTokens: 100000,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "gpt-5.5": {
        displayName: "GPT-5.5",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_050_000,
          maxOutputTokens: 131_072,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "gpt-5.6-sol": {
        displayName: "GPT-5.6 Sol",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_050_000,
          maxOutputTokens: 131_072,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["gpt-5.6"],
      },
      "o4-mini": {
        displayName: "o4 Mini",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 200_000,
          maxOutputTokens: 100_000,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
    },
  },

  // ── Alibaba Cloud Model Studio / DashScope ────────────────────────────

  dashscope: {
    displayName: "阿里云百炼 (DashScope)",
    protocol: "openai",
    defaultUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    apiKeyEnvVar: "DASHSCOPE_API_KEY",
    models: {
      "qwen3.7-max": {
        displayName: "Qwen3.7 Max",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 65_536,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 10,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "qwen3.8-max": {
        displayName: "Qwen3.8 Max",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 131_072,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 10,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "qwen3.7-plus": {
        displayName: "Qwen3.7 Plus",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 65_536,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 10,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "qwen3.6-flash": {
        displayName: "Qwen3.6 Flash",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 65_536,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "qwen-max": {
        displayName: "Qwen Max",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 131_072,
          maxOutputTokens: 2_000,
        },
        multimodal: { input: ["text"] },
        aliases: ["qwen-max-latest"],
      },
      "qwen-plus": {
        displayName: "Qwen Plus",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 131_072,
          maxOutputTokens: 2_000,
        },
        multimodal: { input: ["text"] },
        aliases: ["qwen-plus-latest"],
      },
      "qwen-turbo": {
        displayName: "Qwen Turbo",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 131_072,
          maxOutputTokens: 1_500,
        },
        multimodal: { input: ["text"] },
        aliases: ["qwen-turbo-latest"],
      },
    },
  },

  // ── DeepSeek ───────────────────────────────────────────────────────────
  // 现行模型（官方文档 2026 年中）：deepseek-v4-pro / deepseek-v4-flash。
  // v4 默认思考（thinking.type + reasoning_effort），支持 prompt cache。
  // deepseek-chat / deepseek-reasoner 已从官方文档下线，保留仅为兼容存量配置。

  deepseek: {
    displayName: "DeepSeek",
    protocol: "openai",
    defaultUrl: "https://api.deepseek.com/v1",
    apiKeyEnvVar: "DEEPSEEK_API_KEY",
    models: {
      "deepseek-chat": {
        // Deprecated: 官方文档已下线，保留兼容存量配置（别名旧 v3 语义）。
        displayName: "DeepSeek Chat (Deprecated)",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1048576,
          maxOutputTokens: 393216,
        },
        multimodal: { input: ["text"] },
        aliases: ["deepseek-v3"],
      },
      "deepseek-reasoner": {
        // Deprecated: 官方文档已下线，保留兼容存量配置。
        displayName: "DeepSeek Reasoner (Deprecated)",
        capabilities: {
          supportsToolUse: false,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: true,
          supportsJsonSchema: false,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1048576,
          maxOutputTokens: 393216,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "deepseek-v4-pro": {
        displayName: "DeepSeek V4 Pro",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true, // 默认思考，thinking.type + reasoning_effort（现 high/max）
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true, // usage.prompt_cache_hit_tokens
          maxContextTokens: 1048576,
          maxOutputTokens: 393216,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "deepseek-v4-flash": {
        displayName: "DeepSeek V4 Flash",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true, // 默认思考，thinking.type + reasoning_effort（low/high/max）
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true, // usage.prompt_cache_hit_tokens
          maxContextTokens: 1048576,
          maxOutputTokens: 393216,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
    },
  },

  // ── Google / Gemini ────────────────────────────────────────────────────

  google: {
    displayName: "Google AI (Gemini)",
    protocol: "google",
    defaultUrl: "https://generativelanguage.googleapis.com",
    apiKeyEnvVar: "GEMINI_API_KEY",
    models: {
      "gemini-2.0-flash": {
        displayName: "Gemini 2.0 Flash",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1048576,
          maxOutputTokens: 65536,
        },
        multimodal: {
          input: ["text", "image", "audio", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["gemini-2.0-flash-001"],
      },
      "gemini-2.5-flash": {
        displayName: "Gemini 2.5 Flash",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1048576,
          maxOutputTokens: 65536,
        },
        multimodal: {
          input: ["text", "image", "audio", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "gemini-2.5-pro": {
        displayName: "Gemini 2.5 Pro",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1048576,
          maxOutputTokens: 65536,
        },
        multimodal: {
          input: ["text", "image", "audio", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "gemini-3.1-pro-preview": {
        displayName: "Gemini 3.1 Pro Preview",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1048576,
          maxOutputTokens: 65536,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["gemini-3.1-pro", "gemini-3-pro"],
      },
      "gemini-3.6-flash": {
        displayName: "Gemini 3.6 Flash",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1048576,
          maxOutputTokens: 65536,
        },
        multimodal: {
          input: ["text", "image", "audio", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["gemini-3-flash"],
      },
      "gemini-3-flash-preview": {
        displayName: "Gemini 3 Flash Preview",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1048576,
          maxOutputTokens: 65536,
        },
        multimodal: {
          input: ["text", "image", "audio", "pdf"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "gemini-3.1-flash-lite": {
        displayName: "Gemini 3.1 Flash Lite",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1048576,
          maxOutputTokens: 65536,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 10,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
    },
  },

  // ── MiniMax ────────────────────────────────────────────────────────────

  minimax: {
    displayName: "MiniMax",
    protocol: "openai",
    defaultUrl: "https://api.minimaxi.com/v1",
    apiKeyEnvVar: "MINIMAX_API_KEY",
    models: {
      "MiniMax-M2.5": {
        displayName: "MiniMax M2.5",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 204_800,
          maxOutputTokens: 16384,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["minimax-m2.5"],
      },
      "MiniMax-M2.7-highspeed": {
        displayName: "MiniMax M2.7 Highspeed",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 204_800,
          maxOutputTokens: 16384,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "MiniMax-M3": {
        displayName: "MiniMax M3",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 1_000_000,
          maxOutputTokens: 131_072,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["minimax-m3"],
      },
    },
  },

  // ── Moonshot / Kimi ────────────────────────────────────────────────────
  // 现行模型（官方文档 2026 年中）：kimi-k3（旗舰，始终思考不可关闭）、
  // kimi-k2.7-code(-highspeed)、kimi-k2.6（思考+非思考）。
  // moonshot-v1 / kimi-k2.5 已于 2026-08-31 下线，不在此收录。

  moonshot: {
    displayName: "Moonshot AI (Kimi)",
    protocol: "openai",
    defaultUrl: "https://api.moonshot.cn/v1",
    apiKeyEnvVar: "MOONSHOT_API_KEY",
    models: {
      "kimi-k3": {
        // 旗舰：始终思考不可关闭（reasoning_effort low/high/max，默认 max）；
        // 自动上下文缓存（prompt > 256 tokens 命中）；官方另支持视频输入，
        // 待 InputModality 扩展 video 后补充。
        displayName: "Kimi K3",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: true,
          maxContextTokens: 1048576,
          maxOutputTokens: 1048576,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["moonshotai/kimi-k3"],
      },
      "kimi-k2.7-code": {
        // 代码/agent 场景：仅思考模式（始终思考），256K 上下文。
        displayName: "Kimi K2.7 Code",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 262144,
          maxOutputTokens: 8192,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["moonshotai/kimi-k2.7-code"],
      },
      "kimi-k2.7-code-highspeed": {
        // 仅思考模式（始终思考），256K 上下文，高吞吐版本。
        displayName: "Kimi K2.7 Code Highspeed",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 262144,
          maxOutputTokens: 8192,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["moonshotai/kimi-k2.7-code-highspeed"],
      },
      "kimi-k2.6": {
        displayName: "Kimi K2.6",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true, // 支持思考+非思考双模式
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 262144,
          maxOutputTokens: 8192,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 20,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/gif", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["moonshotai/kimi-k2.6"],
      },
    },
  },

  // ── Volcano Ark (火山方舟) ────────────────────────────────────────────

  volc_ark: {
    displayName: "火山方舟 (Volcano Ark)",
    protocol: "openai",
    defaultUrl: "https://ark.cn-beijing.volces.com/api/v3",
    apiKeyEnvVar: "VOLC_ARK_API_KEY",
    models: {
      "doubao-1.5-pro-256k": {
        displayName: "Doubao 1.5 Pro 256K",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 262144,
          maxOutputTokens: 16384,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 10,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "doubao-1.5-pro": {
        displayName: "Doubao 1.5 Pro",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 131072,
          maxOutputTokens: 16384,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 10,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/webp"],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "doubao-1.5-lite-128k": {
        displayName: "Doubao 1.5 Lite 128K",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 131072,
          maxOutputTokens: 8192,
        },
        multimodal: {
          input: ["text"],
          maxImagesPerRequest: 0,
          supportedImageMimeTypes: [],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "doubao-1.5-lite": {
        displayName: "Doubao 1.5 Lite",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 32768,
          maxOutputTokens: 8192,
        },
        multimodal: {
          input: ["text"],
          maxImagesPerRequest: 0,
          supportedImageMimeTypes: [],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "deepseek-r1": {
        displayName: "DeepSeek R1 (Volc)",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 65536,
          maxOutputTokens: 16384,
        },
        multimodal: {
          input: ["text"],
          maxImagesPerRequest: 0,
          supportedImageMimeTypes: [],
          imageDetail: "auto",
        },
        aliases: [],
      },
      "seed-2.0-pro": {
        displayName: "Seed 2.0 Pro",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 262_144,
          maxOutputTokens: 16_384,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 10,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["doubao-seed-2.0-pro", "seed-2.0-pro-256k"],
      },
      "seed-1.8-pro": {
        displayName: "Seed 1.8 Pro",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 262_144,
          maxOutputTokens: 16_384,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 10,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["doubao-seed-1.8-pro"],
      },
      "seed-1.6-pro": {
        displayName: "Seed 1.6 Pro",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 262_144,
          maxOutputTokens: 16_384,
        },
        multimodal: {
          input: ["text", "image"],
          maxImagesPerRequest: 10,
          supportedImageMimeTypes: ["image/jpeg", "image/png", "image/webp"],
          imageDetail: "auto",
        },
        aliases: ["doubao-seed-1.6-pro"],
      },
    },
  },

  // ── Zhipu / Z.AI ───────────────────────────────────────────────────────

  zhipu: {
    displayName: "智谱 Z.AI",
    protocol: "openai",
    defaultUrl: "https://api.z.ai/api/paas/v4",
    apiKeyEnvVar: "ZAI_API_KEY",
    models: {
      "glm-5.2": {
        displayName: "GLM-5.2",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_048_576,
          maxOutputTokens: 131_072,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "glm-5.1": {
        displayName: "GLM-5.1",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 1_048_576,
          maxOutputTokens: 131_072,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "glm-5-turbo": {
        displayName: "GLM-5 Turbo",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 131_072,
          maxOutputTokens: 65_536,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "glm-4.6": {
        displayName: "GLM-4.6",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 131_072,
          maxOutputTokens: 65_536,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "glm-4.7": {
        displayName: "GLM-4.7",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 200_000,
          maxOutputTokens: 131_072,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "glm-4.7-flashx": {
        displayName: "GLM-4.7 FlashX",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 200_000,
          maxOutputTokens: 131_072,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "glm-4.7-flash": {
        displayName: "GLM-4.7 Flash",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: true,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 200_000,
          maxOutputTokens: 131_072,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "glm-4-plus": {
        displayName: "GLM-4 Plus",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 128_000,
          maxOutputTokens: 8_192,
        },
        multimodal: { input: ["text"] },
        aliases: ["GLM-4-Plus"],
      },
      "glm-4-air-250414": {
        displayName: "GLM-4 Air 250414",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 128_000,
          maxOutputTokens: 8_192,
        },
        multimodal: { input: ["text"] },
        aliases: ["GLM-4-Air-250414"],
      },
      "glm-4-airx": {
        displayName: "GLM-4 AirX",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 128_000,
          maxOutputTokens: 8_192,
        },
        multimodal: { input: ["text"] },
        aliases: ["GLM-4-AirX"],
      },
      "glm-4-flashx-250414": {
        displayName: "GLM-4 FlashX 250414",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 128_000,
          maxOutputTokens: 8_192,
        },
        multimodal: { input: ["text"] },
        aliases: ["GLM-4-FlashX-250414"],
      },
      "glm-4-flash-250414": {
        displayName: "GLM-4 Flash 250414",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: true,
          supportsThinking: false,
          supportsJsonSchema: true,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 128_000,
          maxOutputTokens: 8_192,
        },
        multimodal: { input: ["text"] },
        aliases: ["GLM-4-Flash-250414"],
      },
    },
  },

  // ── Proxy providers (no built-in models; use cross-provider lookup) ───

  openrouter: {
    displayName: "OpenRouter",
    protocol: "openai",
    defaultUrl: "https://openrouter.ai/api/v1",
    apiKeyEnvVar: "OPENROUTER_API_KEY",
    models: {},
  },

  ollama: {
    displayName: "Ollama",
    protocol: "openai",
    defaultUrl: "http://localhost:11434/v1",
    models: {
      "qwen3:0.6b": {
        displayName: "Qwen3 0.6B (Ollama)",
        capabilities: {
          supportsToolUse: true,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: false,
          supportsJsonSchema: false,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 40_960,
          maxOutputTokens: 8_192,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "qwen3:8b": {
        displayName: "Qwen3 8B (Ollama)",
        capabilities: {
          supportsToolUse: false,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: false,
          supportsJsonSchema: false,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 40_960,
          maxOutputTokens: 8_192,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
      "llama3.1:8b": {
        displayName: "Llama 3.1 8B (Ollama)",
        capabilities: {
          supportsToolUse: false,
          supportsStreaming: true,
          supportsParallelToolCalls: false,
          supportsThinking: false,
          supportsJsonSchema: false,
          supportsSystemPrompt: true,
          supportsPromptCache: false,
          maxContextTokens: 131_072,
          maxOutputTokens: 8_192,
        },
        multimodal: { input: ["text"] },
        aliases: [],
      },
    },
  },
};
