/**
 * V2 sati.yaml generation for desktop onboarding.
 * Shared with unit tests — keep free of Electron imports.
 */

import { stringify } from "yaml";

export interface OnboardingPayload {
  providerType: string;
  baseUrl: string;
  apiKey: string;
  model: string;
}

const ALLOWED_PROVIDER_TYPES = new Set(["anthropic", "openai-chat", "openai-responses", "litellm", "ccr"]);

/** Gateway V2 schema: anthropic | openai */
export function providerTypeToProtocol(providerType: string): "anthropic" | "openai" {
  return providerType === "anthropic" ? "anthropic" : "openai";
}

/**
 * Writes schemaVersion + agent + model (V2). Matches Web onboarding
 * (LlmConfigurationStep) so loadPilotConfig() accepts fresh installs.
 *
 * 用 yaml.stringify 序列化（而非手工拼串）：modelId/baseUrl/apiKey 含
 * 特殊字符（冒号、井号、换行、控制字符）时自动正确转义，避免产出
 * yaml.parse 拒绝的配置。
 */
export function buildConfigYaml(p: OnboardingPayload): string {
  // 未知 providerType 直接报错而非静默回退 anthropic：回退会写入错误协议的
  // 配置且通过校验，直到运行时每个聊天请求都失败才暴露。
  if (!ALLOWED_PROVIDER_TYPES.has(p.providerType)) {
    throw new TypeError(
      `不支持的 providerType "${p.providerType}"（可选值：${[...ALLOWED_PROVIDER_TYPES].join(", ")}）`,
    );
  }
  const rawType = p.providerType;
  const protocol = providerTypeToProtocol(rawType);
  const providerId = "sati";
  const modelId = p.model.trim();

  const doc = {
    schemaVersion: 1,
    agent: { model: `${providerId}/${modelId}` },
    model: {
      providers: {
        [providerId]: {
          protocol,
          url: p.baseUrl.trim(),
          apiKey: p.apiKey.trim(),
          models: { [modelId]: {} },
        },
      },
    },
  };
  return `# Generated by Sati onboarding\n${stringify(doc)}`;
}
