/**
 * V2 pilotdeck.yaml generation for desktop onboarding.
 * Shared with unit tests — keep free of Electron imports.
 */

export interface OnboardingPayload {
  providerType: string;
  baseUrl: string;
  apiKey: string;
  model: string;
}

const ALLOWED_PROVIDER_TYPES = new Set([
  "anthropic",
  "openai-chat",
  "openai-responses",
  "litellm",
  "ccr",
]);

/** Gateway V2 schema: anthropic | openai */
export function providerTypeToProtocol(
  providerType: string,
): "anthropic" | "openai" {
  return providerType === "anthropic" ? "anthropic" : "openai";
}

function escapeYamlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * Writes schemaVersion + agent + model (V2). Matches Web onboarding
 * (LlmConfigurationStep) so loadPilotConfig() accepts fresh installs.
 */
export function buildConfigYaml(p: OnboardingPayload): string {
  const rawType = ALLOWED_PROVIDER_TYPES.has(p.providerType)
    ? p.providerType
    : "anthropic";
  const protocol = providerTypeToProtocol(rawType);
  const providerId = "pilotdeck";
  const modelId = p.model.trim();

  return [
    "# Generated by PilotDeck onboarding",
    "schemaVersion: 1",
    "agent:",
    `  model: ${providerId}/${modelId}`,
    "model:",
    "  providers:",
    `    ${providerId}:`,
    `      protocol: ${protocol}`,
    `      url: ${escapeYamlString(p.baseUrl.trim())}`,
    `      apiKey: ${escapeYamlString(p.apiKey.trim())}`,
    "      models:",
    `        ${modelId}: {}`,
    "",
  ].join("\n");
}
