/**
 * src/patent/figuregen — Graphviz 可选渲染器测试（DOT 生成 + SVG 加工 + 回读）。
 *
 * DOT 生成与 SVG 加工为纯函数，无需 dot 二进制即可测；真机集成用例在缺 graphviz
 * 的环境自动 skip。黑白合规不变式（指南一部一章 4.3/4.6）与 data-ref 注入的
 * fail-closed 行为在此固化。
 */

import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { buildFigureDot, dotEscape } from "../../../src/patent/figuregen/dot.js";
import { parseFigureSvg } from "../../../src/patent/figuregen/readback.js";
import {
  postProcessGraphvizSvg,
  renderFigureSvgWithGraphviz,
  resolveDotBinary,
} from "../../../src/patent/figuregen/render-graphviz.js";
import type { FigureSpec } from "../../../src/patent/figuregen/types.js";

const SPEC: FigureSpec = {
  figure_no: 1,
  kind: "flowchart",
  nodes: [
    { id: "start", label: "开始", shape: "ellipse" },
    { id: "step", label: "处理模块(20)", ref: 20 },
    { id: "check", label: "通过?", shape: "diamond" },
  ],
  edges: [
    { from: "start", to: "step" },
    { from: "step", to: "check", label: "是", dashed: true },
  ],
};

test("DOT：同输入逐字节一致（快照确定性）", () => {
  assert.equal(buildFigureDot(SPEC), buildFigureDot(SPEC));
});

test("DOT：黑白合规属性、方向与图号标注固化在源里", () => {
  const dot = buildFigureDot(SPEC);
  assert.ok(dot.includes('bgcolor="#FFFFFF"'));
  assert.ok(dot.includes('color="#000000"'));
  assert.ok(dot.includes('fillcolor="#FFFFFF"'));
  assert.ok(!/gradient/i.test(dot));
  assert.ok(dot.includes('rankdir="TB"'), "flowchart 默认 TB");
  assert.ok(dot.includes('label="图1"'));
  assert.ok(dot.includes('labelloc="b"'));
});

test("DOT：shape 映射、边标签与虚线", () => {
  const dot = buildFigureDot(SPEC);
  assert.ok(dot.includes('shape="ellipse"'));
  assert.ok(dot.includes('shape="diamond"'));
  assert.ok(dot.includes('shape="box"'));
  assert.ok(dot.includes('label="是"'));
  assert.ok(dot.includes("style=dashed"));

  const block: FigureSpec = {
    figure_no: 2,
    kind: "block",
    nodes: [
      { id: "db", label: "存储(30)", shape: "cylinder", ref: 30 },
      { id: "io", label: "输入(40)", shape: "parallelogram", ref: 40 },
      { id: "r", label: "起", shape: "round" },
    ],
    edges: [],
  };
  const blockDot = buildFigureDot(block);
  assert.ok(blockDot.includes('rankdir="LR"'), "block 默认 LR");
  assert.ok(blockDot.includes('shape="cylinder"'));
  assert.ok(blockDot.includes('shape="parallelogram"'));
  assert.ok(blockDot.includes('style="rounded,filled"'));
});

test("DOT：label 与节点 id 转义（引号/反斜杠/换行）", () => {
  assert.equal(dotEscape('a"b\\c\nd'), 'a\\"b\\\\c\\nd');
  const dot = buildFigureDot({
    figure_no: 1,
    kind: "flowchart",
    nodes: [{ id: 'n"1', label: '说"明"\n第二行' }],
    edges: [],
  });
  assert.ok(dot.includes('"n\\"1"'), "节点 id 以带引号 DOT id 传递");
  assert.ok(dot.includes('label="说\\"明\\"\\n第二行"'));
});

test("加工：剥离头部、颜色关键字归一化、data-ref 注入到节点分组", () => {
  const raw = [
    '<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
    '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">',
    "<!-- Generated by graphviz version 99.0 (fake)\n -->",
    '<svg width="196pt" height="259pt"\n viewBox="0.00 0.00 196.00 259.00" xmlns="http://www.w3.org/2000/svg">',
    '<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 254.95)">',
    "<title>图1</title>",
    '<polygon fill="white" stroke="none" points="-4,4 -4,-254.95 192,-254.95 192,4 -4,4"/>',
    '<text xml:space="preserve" text-anchor="middle" x="94" y="-10.95" font-size="14.00">图1</text>',
    "<!-- start -->",
    '<g id="node1" class="node">',
    "<title>start</title>",
    '<ellipse fill="#ffffff" stroke="#000000" cx="99.5" cy="-230.98" rx="31.47" ry="19.98"/>',
    '<text xml:space="preserve" text-anchor="middle" x="99.5" y="-227.8" font-size="14.00" fill="#000000">开始</text>',
    "</g>",
    "<!-- step -->",
    '<g id="node2" class="node">',
    "<title>step</title>",
    '<polygon fill="#ffffff" stroke="#000000" points="99.5,-174 19,-145.75 99.5,-117.5 180,-145.75 99.5,-174"/>',
    '<text xml:space="preserve" text-anchor="middle" x="99.5" y="-142.57" font-size="14.00" fill="#000000">处理模块(20)</text>',
    "</g>",
    "</g>",
    "</svg>",
  ].join("\n");

  const svg = postProcessGraphvizSvg(raw, new Map([["step", 20]]));
  assert.ok(svg.startsWith("<svg"), "XML 声明/DOCTYPE/生成器注释应被剥离");
  assert.ok(!svg.includes("Generated by graphviz"));
  assert.ok(!svg.includes('fill="white"'), "颜色关键字应归一化为十六进制");
  assert.ok(svg.includes('fill="#FFFFFF"'));
  assert.ok(/<g id="node2" class="node" data-ref="20">/.test(svg), "data-ref 注入到节点分组开标签");
  assert.ok(!svg.slice(0, svg.indexOf('id="node2"')).includes("data-ref"), "无标记节点分组不带 data-ref");
});

test("加工：fail-closed——title 缺失或分组结构异常时抛错", () => {
  const raw = '<svg xmlns="http://www.w3.org/2000/svg"><g id="node1" class="node"><text>无 title</text></g></svg>';
  assert.throws(() => postProcessGraphvizSvg(raw, new Map([["step", 20]])), /title.*fail-closed/u);

  // 分组开标签若非 "<g " 形态（如换行书写），就近回溯会落到外层分组，
  // title 与分组之间隔着标签 → 结构异常 fail-closed，绝不注入错位。
  const malformed =
    '<svg xmlns="http://www.w3.org/2000/svg"><g id="graph0" class="graph"><g\nid="node1" class="node"><title>step</title></g></g></svg>';
  assert.throws(() => postProcessGraphvizSvg(malformed, new Map([["step", 20]])), /结构异常/u);
});

test("回读：graphviz 渲染产物（title 取回原 id，graph/edge 分组跳过）", () => {
  const raw = [
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0.00 0.00 196.00 259.00">',
    '<g id="graph0" class="graph">',
    "<title>图1</title>",
    '<text xml:space="preserve" font-size="14.00">图1</text>',
    '<g id="node1" class="node">',
    "<title>start</title>",
    '<text font-size="14.00" fill="#000000">开始</text>',
    "</g>",
    '<g id="node2" class="node" data-ref="20">',
    "<title>step</title>",
    '<text font-size="14.00" fill="#000000">处理模块(20)</text>',
    "</g>",
    '<g id="edge1" class="edge">',
    "<title>start&#45;&gt;step</title>",
    '<path fill="none" stroke="#000000" d="M0,0"/>',
    "</g>",
    "</g>",
    "</svg>",
  ].join("\n");
  const parsed = parseFigureSvg(postProcessGraphvizSvg(raw, new Map([["step", 20]])));
  assert.equal(parsed.figureNo, 1);
  assert.deepEqual(
    parsed.nodes.map(node => [node.id, node.label, node.ref]),
    [
      ["start", "开始", undefined],
      ["step", "处理模块(20)", 20],
    ],
  );
});

test("回读：US 辖区 FIG. N 图号标注可解析", () => {
  const svg =
    '<svg xmlns="http://www.w3.org/2000/svg"><g id="n-a" data-ref="20"><text x="1" y="2">模块(20)</text></g>' +
    '<text text-anchor="middle">FIG. 3</text></svg>';
  const parsed = parseFigureSvg(svg);
  assert.equal(parsed.figureNo, 3);
  assert.equal(parsed.nodes[0].ref, 20);
});

test("回读：caption 取最后一个 text 标注（节点文本含图N字样不误配）", () => {
  const svg =
    '<svg xmlns="http://www.w3.org/2000/svg"><g id="n-a"><text x="1" y="2">流程见图5示意</text></g>' +
    '<text text-anchor="middle">图2</text></svg>';
  assert.equal(parseFigureSvg(svg).figureNo, 2);
});

test("二进制定位：SATI_GRAPHVIZ_DOT 优先，PATH 扫描兜底，缺失返回 null", async t => {
  const fakeDir = mkdtempSync(join(tmpdir(), "sati-dot-path-"));
  writeFileSync(join(fakeDir, "dot"), "#!/bin/sh\n", { mode: 0o755 });
  const savedPath = process.env.PATH;
  t.after(() => {
    process.env.PATH = savedPath;
    delete process.env.SATI_GRAPHVIZ_DOT;
  });

  process.env.PATH = fakeDir;
  delete process.env.SATI_GRAPHVIZ_DOT;
  assert.equal(resolveDotBinary(), join(fakeDir, "dot"));

  process.env.SATI_GRAPHVIZ_DOT = "/custom/path/to/dot";
  assert.equal(resolveDotBinary(), "/custom/path/to/dot", "显式路径优先于 PATH");

  process.env.PATH = "";
  delete process.env.SATI_GRAPHVIZ_DOT;
  assert.equal(resolveDotBinary(), null);
});

test("真机集成：dot 渲染 → data-ref 自检 → 回读还原（无 graphviz 自动 skip）", {
  skip: resolveDotBinary() === null ? "graphviz not installed" : false,
}, async () => {
  const dotPath = resolveDotBinary();
  assert.ok(dotPath);
  const first = await renderFigureSvgWithGraphviz(SPEC);
  const second = await renderFigureSvgWithGraphviz(SPEC);
  assert.equal(first.svg, second.svg, "同输入同机逐字节一致");

  assert.ok(first.svg.includes('data-ref="20"'));
  assert.ok(first.svg.includes("处理模块(20)"));
  assert.ok(!first.svg.includes("Generated by graphviz"), "生成器注释不进入交付物");
  const colors = first.svg.match(/#[0-9a-fA-F]{3,8}\b/g) ?? [];
  for (const color of colors) {
    assert.ok(color.toUpperCase() === "#000000" || color.toUpperCase() === "#FFFFFF", `发现非黑白颜色 ${color}`);
  }
  assert.ok(first.width > 0 && first.height > 0);

  const parsed = parseFigureSvg(first.svg);
  assert.equal(parsed.figureNo, 1);
  const withRef = parsed.nodes.filter(node => node.ref !== undefined);
  assert.deepEqual(
    withRef.map(node => [node.id, node.ref]),
    [["step", 20]],
  );
});

test("真机集成：dot 渲染 US 辖区（FIG. N 标注）", {
  skip: resolveDotBinary() === null ? "graphviz not installed" : false,
}, async () => {
  const { svg } = await renderFigureSvgWithGraphviz({ ...SPEC, figure_no: 3 }, { jurisdiction: "us" });
  assert.match(svg, /<text[^>]*>FIG\. 3<\/text>/u);
});
