/**
 * src/patent/figuregen — Graphviz WASM 后端（render-viz-wasm）测试。
 *
 * 替身 loader 固化三条行为契约：惰性加载、实例只建一次、**失败不缓存**（一次瞬时
 * 失败不得把后续渲染全部钉死）；失败文案必须引导内置渲染器 / 系统 graphviz；
 * 渲染错误原样上抛；已 abort 的 signal 立即拒绝且不触发加载。真机用例只跑一次真实
 * `@viz-js/viz`（无外部依赖），证明 builtin 与 graphviz-wasm 两路产物同过黑白扫描
 * 与 data-ref 回读。
 */

import assert from "node:assert/strict";
import test from "node:test";
import { parseFigureSvg } from "../../../src/patent/figuregen/readback.js";
import { renderFigureSvg } from "../../../src/patent/figuregen/render-svg.js";
import { renderFigureSvgWithGraphviz } from "../../../src/patent/figuregen/render-graphviz.js";
import { createWasmDotRunner, type VizLoader } from "../../../src/patent/figuregen/render-viz-wasm.js";
import type { FigureSpec } from "../../../src/patent/figuregen/types.js";

const SPEC: FigureSpec = {
  figure_no: 1,
  kind: "flowchart",
  nodes: [
    { id: "start", label: "开始", shape: "ellipse" },
    { id: "step", label: "处理模块(20)", ref: 20 },
  ],
  edges: [{ from: "start", to: "step" }],
};

/** 结构仿真 graphviz -Tsvg 输出（头部 + graph0 嵌套分组 + 关键字色），供替身 loader 返还。 */
const CANNED_SVG = [
  '<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
  '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">',
  "<!-- Generated by graphviz version 99.0 (fake) -->",
  '<svg width="150pt" height="120pt" viewBox="0.00 0.00 150.00 120.00" xmlns="http://www.w3.org/2000/svg">',
  '<g id="graph0" class="graph">',
  "<title>图1</title>",
  '<text text-anchor="middle" font-size="14.00">图1</text>',
  '<g id="node1" class="node">',
  "<title>start</title>",
  '<ellipse fill="#ffffff" stroke="#000000" cx="75" cy="-95" rx="27" ry="18"/>',
  '<text text-anchor="middle" fill="#000000">开始</text>',
  "</g>",
  '<g id="node2" class="node">',
  "<title>step</title>",
  '<polygon fill="#ffffff" stroke="#000000" points="100,-40 50,-40 50,-4 100,-4"/>',
  '<text text-anchor="middle" fill="#000000">处理模块(20)</text>',
  "</g>",
  "</g>",
  "</svg>",
].join("\n");

/** 构造替身 @viz-js/viz 模块（暴露异步 instance()）。 */
function fakeVizModule(renderString: (input: string, options: { format: string }) => string): unknown {
  return { instance: async () => ({ renderString }) };
}

/** 复刻 render-graphviz 的黑白不变式，供两路产物共用断言（不导出内部实现）。 */
function assertBlackWhiteSvg(svg: string, label: string): void {
  for (const match of svg.matchAll(/\b(fill|stroke|color)="([^"]*)"/gu)) {
    const value = match[2].trim().toLowerCase();
    if (value === "none" || value === "#000000" || value === "#ffffff") continue;
    assert.fail(`${label}: 出现非黑白颜色 "${match[2]}"`);
  }
  for (const match of svg.matchAll(/#[0-9a-fA-F]{3,8}\b/gu)) {
    const hex = match[0].toUpperCase();
    if (hex === "#000000" || hex === "#FFFFFF") continue;
    assert.fail(`${label}: 出现非黑白颜色 ${hex}`);
  }
}

test("WASM runner：加载成功时实例只建一次并返回 SVG（renderString format=svg）", async () => {
  let instanceCalls = 0;
  let renderCalls = 0;
  let seenFormat = "";
  const seenDots: string[] = [];
  const runner = createWasmDotRunner({
    loadViz: async () => {
      return {
        instance: async () => {
          instanceCalls += 1;
          return {
            renderString: (input: string, options: { format: string }) => {
              renderCalls += 1;
              seenFormat = options.format;
              seenDots.push(input);
              return CANNED_SVG;
            },
          };
        },
      };
    },
  });

  assert.equal(await runner("digraph { a }"), CANNED_SVG);
  assert.equal(await runner("digraph { b }"), CANNED_SVG);
  assert.equal(instanceCalls, 1, "实例创建后缓存复用");
  assert.equal(renderCalls, 2);
  assert.equal(seenFormat, "svg");
  assert.deepEqual(seenDots, ["digraph { a }", "digraph { b }"], "DOT 源逐次原样透传后端");
});

test("WASM runner：加载失败不被缓存（第二次仍尝试）且文案引导内置渲染器/系统 graphviz", async () => {
  let loadCalls = 0;
  const runner = createWasmDotRunner({
    loadViz: async () => {
      loadCalls += 1;
      if (loadCalls === 1) {
        throw new Error("ENOENT: wasm asset missing");
      }
      return fakeVizModule(() => CANNED_SVG);
    },
  });

  await assert.rejects(runner("digraph {}"), (err: unknown) => {
    const message = err instanceof Error ? err.message : String(err);
    assert.match(message, /内置渲染器/u);
    assert.match(message, /系统 graphviz/u);
    assert.match(message, /SATI_FIGURE_RENDERER=builtin/u);
    assert.match(message, /ENOENT: wasm asset missing/u);
    return true;
  });
  assert.equal(loadCalls, 1);

  assert.equal(await runner("digraph {}"), CANNED_SVG, "失败不缓存：第二次应重新加载并成功");
  assert.equal(loadCalls, 2);
});

test("WASM runner：实例化失败同样不被缓存（第二次仍尝试）", async () => {
  let instanceCalls = 0;
  const runner = createWasmDotRunner({
    loadViz: async () => ({
      instance: async () => {
        instanceCalls += 1;
        if (instanceCalls === 1) {
          throw new Error("instantiate boom");
        }
        return { renderString: () => CANNED_SVG };
      },
    }),
  });

  await assert.rejects(runner("digraph {}"), /实例化失败[\s\S]*instantiate boom/u);
  assert.equal(await runner("digraph {}"), CANNED_SVG);
  assert.equal(instanceCalls, 2);
});

test("WASM runner：渲染抛错原样上抛（不包装）", async () => {
  const boom = new Error("syntax error in dot source");
  const runner = createWasmDotRunner({
    loadViz: async () =>
      fakeVizModule(() => {
        throw boom;
      }),
  });
  await assert.rejects(runner("bad dot"), (err: unknown) => {
    assert.equal(err, boom, "渲染错误应原样上抛，不被包装");
    return true;
  });
});

test("WASM runner：已 abort 的 signal 立即拒绝且不触发加载", async () => {
  let loadCalls = 0;
  const loadViz: VizLoader = async () => {
    loadCalls += 1;
    return fakeVizModule(() => CANNED_SVG);
  };
  const runner = createWasmDotRunner({ loadViz });
  const controller = new AbortController();
  controller.abort();

  await assert.rejects(runner("digraph {}", controller.signal), /已取消/u);
  assert.equal(loadCalls, 0, "已 abort 时应立即拒绝，不加载模块");
});

test("WASM runner：经 renderFigureSvgWithGraphviz 加工链（data-ref 注入 + 回读自检）", async () => {
  let seenDot = "";
  const runner = createWasmDotRunner({
    loadViz: async () =>
      fakeVizModule((input: string) => {
        seenDot = input;
        return CANNED_SVG;
      }),
  });

  const { svg, width, height } = await renderFigureSvgWithGraphviz(SPEC, { runner });
  assert.ok(seenDot.includes('"step" [label="处理模块(20)"'), "runner 收到 buildFigureDot 的 DOT");
  assert.ok(svg.startsWith("<svg"), "头部应被剥离");
  assert.ok(!svg.includes("Generated by graphviz"), "生成器注释不进入交付物");
  assert.ok(svg.includes('data-ref="20"'), "data-ref 注入到节点分组");
  assert.ok(width > 0 && height > 0, "画幅由 viewBox 解析");
  const parsed = parseFigureSvg(svg);
  assert.equal(parsed.figureNo, 1);
  assert.deepEqual(
    parsed.nodes.filter(node => node.ref !== undefined).map(node => [node.id, node.ref]),
    [["step", 20]],
  );
});

test("真机 WASM：builtin 与 graphviz-wasm 同 spec 出图，均黑白合规且 data-ref 回读一致", async () => {
  const builtin = renderFigureSvg(SPEC, {}).svg;
  const wasm = (await renderFigureSvgWithGraphviz(SPEC, { runner: createWasmDotRunner() })).svg;

  assertBlackWhiteSvg(builtin, "builtin");
  assertBlackWhiteSvg(wasm, "graphviz-wasm");
  assert.ok(wasm.includes('data-ref="20"'), "WASM 产物 data-ref 注入");

  for (const [label, svg] of [
    ["builtin", builtin],
    ["graphviz-wasm", wasm],
  ] as const) {
    const parsed = parseFigureSvg(svg);
    assert.equal(parsed.figureNo, SPEC.figure_no, label);
    assert.deepEqual(
      parsed.nodes.filter(node => node.ref !== undefined).map(node => [node.id, node.ref]),
      [["step", 20]],
      label,
    );
  }
});
