/**
 * patent_figure_generate 工具层 Graphviz 渲染器测试（SATI_FIGURE_RENDERER 开关）。
 *
 * 进程边界用可执行 node 脚本充当 fake dot（单测不依赖本机 graphviz）；真机集成
 * 用例在 dot.spec.ts。fail-closed 行为：dot 缺失/进程失败/环境变量非法值均报错
 * 而非静默回退。
 */

import assert from "node:assert/strict";
import { chmodSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createPatentFigureGenerateTool } from "../../../src/tool/builtin/patentFigureGenerate.js";
import type { SatiToolRuntimeContext } from "../../../src/tool/protocol/types.js";
import type { FigureSpec } from "../../../src/patent/figuregen/types.js";

function makeContext(cwd: string): SatiToolRuntimeContext {
  return {
    sessionId: "sess-test",
    turnId: "turn-1",
    cwd,
    permissionMode: "bypassPermissions",
    permissionContext: {
      mode: "bypassPermissions",
      rules: { allow: [], deny: [], ask: [] },
      cwd,
      additionalWorkingDirectories: [],
      canPrompt: false,
      bypassAvailable: true,
    },
  };
}

const FIG: FigureSpec = {
  figure_no: 1,
  kind: "flowchart",
  nodes: [
    { id: "start", label: "开始", shape: "ellipse" },
    { id: "step", label: "处理模块(20)", ref: 20 },
  ],
  edges: [{ from: "start", to: "step" }],
};

/** 结构仿真 dot 输出（真机 graphviz -Tsvg 形态：头部注释、graph0 嵌套分组、关键字色）。 */
const CANNED_SVG = [
  '<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
  "<!-- Generated by graphviz version 99.0 (fake)\n -->",
  '<svg width="150pt" height="120pt" viewBox="0.00 0.00 150.00 120.00" xmlns="http://www.w3.org/2000/svg">',
  '<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 116)">',
  "<title>图1</title>",
  '<polygon fill="white" stroke="none" points="-4,4 -4,-116 146,-116 146,4 -4,4"/>',
  '<text xml:space="preserve" text-anchor="middle" font-size="14.00">图1</text>',
  '<g id="node1" class="node">',
  "<title>start</title>",
  '<ellipse fill="#ffffff" stroke="#000000" cx="75" cy="-95" rx="27" ry="18"/>',
  '<text xml:space="preserve" text-anchor="middle" font-size="14.00" fill="#000000">开始</text>',
  "</g>",
  '<g id="node2" class="node">',
  "<title>step</title>",
  '<polygon fill="#ffffff" stroke="#000000" points="100,-40 50,-40 50,-4 100,-4 100,-40"/>',
  '<text xml:space="preserve" text-anchor="middle" font-size="14.00" fill="#000000">处理模块(20)</text>',
  "</g>",
  '<g id="edge1" class="edge">',
  "<title>start&#45;&gt;step</title>",
  '<path fill="none" stroke="#000000" d="M75,-76.6C75,-68.5 75,-58.7 75,-50.2"/>',
  "</g>",
  "</g>",
  "</svg>",
].join("\n");

/** 可执行 node 脚本伪装的 dot：吞掉 stdin，输出固定 SVG（或按脚本参数失败）。 */
function writeFakeDot(dir: string, name: string, behavior: "emit" | "fail"): string {
  const script =
    behavior === "emit"
      ? [
          "#!/usr/bin/env node",
          'let input = "";',
          'process.stdin.setEncoding("utf8");',
          'process.stdin.on("data", chunk => { input += chunk; });',
          'process.stdin.on("end", () => { process.stdout.write(process.env.FAKE_DOT_OUTPUT ?? ""); });',
        ].join("\n")
      : [
          "#!/usr/bin/env node",
          "process.stdin.resume();",
          'process.stderr.write("syntax error in dot source\\n");',
          "process.exit(1);",
        ].join("\n");
  const path = join(dir, name);
  writeFileSync(path, script + "\n", { mode: 0o755 });
  chmodSync(path, 0o755);
  return path;
}

/** 临时改写环境变量并在结束后恢复。 */
async function withEnv(values: Record<string, string | undefined>, run: () => Promise<void>): Promise<void> {
  const saved = new Map<string, string | undefined>();
  for (const [key, value] of Object.entries(values)) {
    saved.set(key, process.env[key]);
    if (value === undefined) {
      delete process.env[key];
    } else {
      process.env[key] = value;
    }
  }
  try {
    await run();
  } finally {
    for (const [key, value] of saved) {
      if (value === undefined) {
        delete process.env[key];
      } else {
        process.env[key] = value;
      }
    }
  }
}

test("patent_figure_generate：SATI_FIGURE_RENDERER=graphviz 经 dot 渲染并加工交付", async () => {
  const cwd = mkdtempSync(join(tmpdir(), "sati-figuregen-gv-"));
  const dotDir = mkdtempSync(join(tmpdir(), "sati-fake-dot-"));
  try {
    const dotPath = writeFakeDot(dotDir, "dot", "emit");
    await withEnv(
      { SATI_FIGURE_RENDERER: "graphviz", SATI_GRAPHVIZ_DOT: dotPath, FAKE_DOT_OUTPUT: CANNED_SVG },
      async () => {
        const tool = createPatentFigureGenerateTool();
        const result = await tool.execute({ figures: [FIG], output_name: "gv" }, makeContext(cwd));
        const svgPath = join(cwd, ".sati", "figures", "gv-fig1.svg");
        assert.ok(existsSync(svgPath));
        const svg = readFileSync(svgPath, "utf8");
        assert.ok(svg.startsWith("<svg"), "头部应被剥离");
        assert.ok(!svg.includes("Generated by graphviz"), "生成器注释不进入交付物");
        assert.ok(svg.includes('data-ref="20"'), "data-ref 注入");
        assert.ok(svg.includes('fill="#FFFFFF"'), "颜色关键字归一化");
        assert.ok(!svg.includes('fill="white"'));
        const text = result.content[0].type === "text" ? result.content[0].text : "";
        assert.ok(text.includes("渲染器: graphviz"), text);
      },
    );
  } finally {
    rmSync(cwd, { recursive: true, force: true });
    rmSync(dotDir, { recursive: true, force: true });
  }
});

test("patent_figure_generate：graphviz 渲染器下 format=both 的 HTML 内嵌 dot 产物", async () => {
  const cwd = mkdtempSync(join(tmpdir(), "sati-figuregen-gv-"));
  const dotDir = mkdtempSync(join(tmpdir(), "sati-fake-dot-"));
  try {
    const dotPath = writeFakeDot(dotDir, "dot", "emit");
    await withEnv(
      { SATI_FIGURE_RENDERER: "graphviz", SATI_GRAPHVIZ_DOT: dotPath, FAKE_DOT_OUTPUT: CANNED_SVG },
      async () => {
        const tool = createPatentFigureGenerateTool();
        await tool.execute({ figures: [FIG], output_name: "gvhtml", format: "both" }, makeContext(cwd));
        const html = readFileSync(join(cwd, ".sati", "figures", "gvhtml-figures.html"), "utf8");
        assert.ok(html.includes("@page"));
        assert.ok(html.includes('data-ref="20"'));
      },
    );
  } finally {
    rmSync(cwd, { recursive: true, force: true });
    rmSync(dotDir, { recursive: true, force: true });
  }
});

test("patent_figure_generate：graphviz 缺失时 fail-closed（不静默回退）", async () => {
  const cwd = mkdtempSync(join(tmpdir(), "sati-figuregen-gv-"));
  try {
    await withEnv({ SATI_FIGURE_RENDERER: "graphviz", SATI_GRAPHVIZ_DOT: undefined, PATH: "" }, async () => {
      const tool = createPatentFigureGenerateTool();
      await assert.rejects(
        tool.execute({ figures: [FIG], output_name: "nodot" }, makeContext(cwd)),
        /未找到 graphviz dot/u,
      );
    });
  } finally {
    rmSync(cwd, { recursive: true, force: true });
  }
});

test("patent_figure_generate：dot 进程失败透出退出码与 stderr", async () => {
  const cwd = mkdtempSync(join(tmpdir(), "sati-figuregen-gv-"));
  const dotDir = mkdtempSync(join(tmpdir(), "sati-fake-dot-"));
  try {
    const dotPath = writeFakeDot(dotDir, "dot", "fail");
    await withEnv({ SATI_FIGURE_RENDERER: "graphviz", SATI_GRAPHVIZ_DOT: dotPath }, async () => {
      const tool = createPatentFigureGenerateTool();
      await assert.rejects(
        tool.execute({ figures: [FIG], output_name: "fail" }, makeContext(cwd)),
        /退出码 1[\s\S]*syntax error/u,
      );
    });
  } finally {
    rmSync(cwd, { recursive: true, force: true });
    rmSync(dotDir, { recursive: true, force: true });
  }
});

test("patent_figure_generate：SATI_FIGURE_RENDERER 非法值 fail-closed", async () => {
  const cwd = mkdtempSync(join(tmpdir(), "sati-figuregen-gv-"));
  try {
    await withEnv({ SATI_FIGURE_RENDERER: "graphviz2" }, async () => {
      const tool = createPatentFigureGenerateTool();
      await assert.rejects(
        tool.execute({ figures: [FIG], output_name: "bad" }, makeContext(cwd)),
        /非法 SATI_FIGURE_RENDERER.*builtin, graphviz/u,
      );
    });
  } finally {
    rmSync(cwd, { recursive: true, force: true });
  }
});

test("patent_figure_generate：env 未设时走内置渲染器（本机装了 graphviz 也不改变默认）", async () => {
  const cwd = mkdtempSync(join(tmpdir(), "sati-figuregen-gv-"));
  try {
    await withEnv({ SATI_FIGURE_RENDERER: undefined }, async () => {
      const tool = createPatentFigureGenerateTool();
      await tool.execute({ figures: [FIG], output_name: "builtin" }, makeContext(cwd));
      const svg = readFileSync(join(cwd, ".sati", "figures", "builtin-fig1.svg"), "utf8");
      assert.ok(svg.includes('id="n-start"'), "内置渲染器分组 id 形态");
      assert.ok(svg.includes('data-ref="20"'));
    });
  } finally {
    rmSync(cwd, { recursive: true, force: true });
  }
});
