/**
 * 文档事实层生成器 / 门禁（doc-claims）。
 *
 * 解决的是审计里最普遍的一类漂移：**文档里手写的版本号与计数**在代码演进后无人回填
 * （README 长期停在 0.1.4、指南写 46 个工具而实际 50、23 个专利工具而实际 26……）。
 *
 * 两种作用域：
 *   1. 整文件生成 `docs/code-facts.md`——版本矩阵 / 计数矩阵 / `src/` 模块索引 / 门禁与
 *      CI 清单，是"入库的、受门禁覆盖的指南事实层"（本地 CLAUDE.md 指向它，不再各自
 *      维护一份易腐数字）；
 *   2. 叙述性文档里的 marker：`<!-- claim:id -->值<!-- /claim -->`，`--write` 回填、
 *      `--check` 断言（CI 门禁，挂 `pnpm lint`）。
 *
 * 刻意**不**扫描 `docs/notes/**`：决策记录是时间点快照，其中的数字反映当时事实，
 * 不应被回填成今天的值。
 *
 * 用法：
 *   pnpm gen:doc-claims            # 回填 marker + 重写 docs/code-facts.md
 *   pnpm check:doc-claims          # 比对（CI）
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { exit } from "node:process";
import { pathToFileURL } from "node:url";
import { CLAIMS, REPO_ROOT, claimById, resolveAllClaims, type DocClaim } from "./doc-claims/resolvers.js";

const FACTS_PATH = "docs/code-facts.md";
const MARKER_RE = /<!--\s*claim:([A-Za-z0-9_-]+)\s*-->([\s\S]*?)<!--\s*\/claim\s*-->/g;
const SKIP_DIRS = new Set(["notes", "node_modules"]);
const CHECK_ONLY = process.argv.includes("--check");

function markdownFiles(relativeDir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(join(REPO_ROOT, relativeDir)).sort()) {
    if (SKIP_DIRS.has(entry)) continue;
    const child = `${relativeDir}/${entry}`;
    if (statSync(join(REPO_ROOT, child)).isDirectory()) markdownFiles(child, out);
    else if (entry.endsWith(".md")) out.push(child);
  }
  return out;
}

function targetDocs(): string[] {
  const rootDocs = readdirSync(REPO_ROOT)
    .filter(entry => entry.endsWith(".md") && statSync(join(REPO_ROOT, entry)).isFile())
    .map(entry => entry);
  return [...rootDocs, ...markdownFiles("docs")].sort();
}

function lineOf(text: string, index: number): number {
  return text.slice(0, index).split("\n").length;
}

/** 门禁链上的 check:* 脚本名（保持 package.json 中的顺序）。 */
function lintGates(): string[] {
  const parsed = JSON.parse(readFileSync(join(REPO_ROOT, "package.json"), "utf8")) as {
    scripts: Record<string, string>;
  };
  return [...(parsed.scripts.lint ?? "").matchAll(/\bpnpm (check:[a-z0-9-]+)/g)].map(match => match[1] ?? "");
}

function ciJobs(): string[] {
  const lines = readFileSync(join(REPO_ROOT, ".github/workflows/ci.yml"), "utf8").split("\n");
  const jobsIndex = lines.findIndex(line => /^jobs:\s*$/.test(line));
  const jobs: string[] = [];
  for (let i = jobsIndex + 1; i < lines.length; i += 1) {
    const line = lines[i] ?? "";
    if (/^\S/.test(line)) break;
    const match = /^ {2}([A-Za-z0-9_-]+):\s*$/.exec(line);
    if (match?.[1] !== undefined) jobs.push(match[1]);
  }
  return jobs;
}

function claimRow(claim: DocClaim, values: Map<string, string>): string {
  return `| \`${claim.id}\` | ${claim.label} | \`${values.get(claim.id) ?? "?"}\` | ${claim.sources.join("；")} |`;
}

function renderFacts(values: Map<string, string>): string {
  const byId = (id: string): string => values.get(id) ?? "?";
  const versionIds = [
    "app_version",
    "node_engine",
    "pnpm_version",
    "typescript_version",
    "protocol_version",
    "protocol_release_count",
    "gateway_method_count",
  ];
  const countIds = [
    "default_tool_count",
    "patent_tool_count",
    "channel_adapter_count",
    "skill_count",
    "role_skill_count",
    "patent_skill_count",
    "src_module_count",
    "loop_module_count",
    "patent_atom_count",
    "patent_manifest_count",
    "drafting_stage_count",
    "event_total_count",
    "lint_gate_count",
    "ci_job_count",
  ];
  const row = (id: string): string => {
    const claim = claimById(id);
    if (claim === undefined) throw new Error(`未知 claim: ${id}`);
    return claimRow(claim, values);
  };

  return [
    "<!-- Generated by scripts/gen-doc-claims.ts - do not edit by hand. Run `pnpm gen:doc-claims` to regenerate. -->",
    "",
    "# 代码事实层（doc-claims）",
    "",
    "本文件由 `scripts/gen-doc-claims.ts` 从代码现算生成，是 **版本号、计数、`src/` 模块索引** 的",
    "唯一事实源：叙述性文档（README / CONTRIBUTING / AGENTS.md / docs/*.md）里的数字以",
    "`<!-- claim:id -->值<!-- /claim -->` 形式引用本表并由 `pnpm check:doc-claims`（挂 `pnpm lint`）",
    "断言；`pnpm check:doc-claims` 也会比对本文件本身，手改即红。",
    "",
    "改代码后运行 `pnpm gen:doc-claims` 回填，然后提交两处（代码 + 本文档）。",
    "",
    "## 1. 版本矩阵",
    "",
    "| claim | 事实 | 值 | 来源 |",
    "| --- | --- | --- | --- |",
    ...versionIds.map(row),
    "",
    "## 2. 计数矩阵",
    "",
    "| claim | 事实 | 值 | 来源 |",
    "| --- | --- | --- | --- |",
    ...countIds.map(row),
    "",
    "## 3. `src/` 模块索引",
    "",
    byId("src_module_list"),
    "",
    "## 4. 门禁链与 CI",
    "",
    `\`pnpm lint\` 在 eslint + UI lint 之后挂 **${byId("lint_gate_count")}** 个领域门禁（按执行顺序）：`,
    "",
    ...lintGates().map(name => `- \`pnpm ${name}\``),
    "",
    `CI（\`.github/workflows/ci.yml\`）共 **${byId("ci_job_count")}** 个 job：`,
    "",
    ...ciJobs().map(name => `- \`${name}\``),
    "",
    "## 5. 维护约定",
    "",
    "- 新增 `src/` 模块：在 `scripts/doc-claims/resolvers.ts` 的 `MODULE_NOTES` 登记一行职责，",
    "  否则 `src_module_list` 解析抛错（模块索引不可能再漏列）。",
    "- 新增 claim：在 `CLAIMS` 里加一条解析器，然后在需要的文档里打 marker。",
    "- 只登记**低频变化**的事实：像「AgentLoop.ts 行数」「测试文件数」这类几乎每个 PR 都会动的数字",
    "  不进本表——它们的引用者会在每次无害改动时被门禁拦下（行数基线由 `docs/technical-debt/metrics.md`",
    "  的 `measure:update` 负责）。",
    "- 不把**运行时数据**（`knowledge.db` 的节点/判例/向量规模）写成本表的 claim——它们不在仓库内，",
    "  无法机械核对，只能在文档里以「运行时数据」口径声明。",
    "",
  ].join("\n");
}

export type MarkerIssue = { file: string; line: number; message: string };

export type MarkerHit = {
  id: string;
  /** 整段标记原文（回填时据此定位）。 */
  full: string;
  expected: string;
  actual: string;
};

export type MarkerScan = { issues: MarkerIssue[]; hits: MarkerHit[] };

/**
 * 纯函数核心：扫描一段文本里的 claim 标记，比对现算值。
 * 抽出来是为了可测（`tests/scripts/doc-claims.spec.ts` 用 fixture 证明它会红）。
 */
export function scanMarkers(file: string, text: string, values: Map<string, string>): MarkerScan {
  const issues: MarkerIssue[] = [];
  const hits: MarkerHit[] = [];
  for (const match of text.matchAll(MARKER_RE)) {
    const [full, id, rawValue] = match;
    const line = lineOf(text, match.index ?? 0);
    const claim = id === undefined ? undefined : claimById(id);
    if (claim === undefined) {
      issues.push({
        file,
        line,
        message: `未知 claim id "${String(id)}"（标记语法：HTML 注释包裹的 claim:id 与 /claim 一对）`,
      });
      continue;
    }
    const actual = (rawValue ?? "").trim();
    if (actual.includes("<!--")) {
      // 值里又出现标记起始符 = 未闭合/嵌套（例如文档里演示标记语法却漏了配对），
      // 非贪婪匹配会一路吞到下一个 `-->`，必须显式报错而不是静默改写正文。
      issues.push({ file, line, message: `claim ${claim.id} 的标记未正确闭合（值内出现 "<!--"）` });
      continue;
    }
    const expected = values.get(claim.id) ?? "";
    hits.push({ id: claim.id, full: full ?? "", expected, actual });
    if (actual !== expected) {
      issues.push({
        file,
        line,
        message: `claim ${claim.id} 过期：文档 "${actual}" ≠ 代码 "${expected}"（来源：${claim.sources.join("；")}）——跑 \`pnpm gen:doc-claims\` 回填`,
      });
    }
  }
  return { issues, hits };
}

function main(): void {
  const values = resolveAllClaims();
  const issues: MarkerIssue[] = [];
  const files = targetDocs();
  let markerCount = 0;
  const touched: string[] = [];

  for (const file of files) {
    if (file === FACTS_PATH) continue;
    const original = readFileSync(join(REPO_ROOT, file), "utf8");
    const scan = scanMarkers(file, original, values);
    issues.push(...scan.issues);
    markerCount += scan.hits.length;
    if (CHECK_ONLY) continue;
    let updated = original;
    for (const hit of scan.hits) {
      if (hit.actual !== hit.expected)
        updated = updated.replace(hit.full, `<!-- claim:${hit.id} -->${hit.expected}<!-- /claim -->`);
    }
    if (updated !== original) {
      writeFileSync(join(REPO_ROOT, file), updated);
      touched.push(file);
    }
  }

  const generated = renderFacts(values);
  const factsExists = existsSync(join(REPO_ROOT, FACTS_PATH));
  const currentFacts = factsExists ? readFileSync(join(REPO_ROOT, FACTS_PATH), "utf8") : "";
  if (CHECK_ONLY) {
    if (generated !== currentFacts) {
      issues.push({
        file: FACTS_PATH,
        line: 1,
        message: "内容与代码不一致（跑 `pnpm gen:doc-claims` 重新生成）",
      });
    }
  } else if (generated !== currentFacts) {
    writeFileSync(join(REPO_ROOT, FACTS_PATH), generated);
    touched.push(FACTS_PATH);
  }

  if (CHECK_ONLY) {
    if (issues.length > 0) {
      console.error(`gen-doc-claims: ${issues.length} 处不一致`);
      for (const issue of issues) console.error(`  - ${issue.file}:${issue.line} ${issue.message}`);
      exit(1);
    }
    console.log(`gen-doc-claims: fresh（${CLAIMS.length} claims，${markerCount} markers，${files.length} 文件）`);
    return;
  }

  console.log(
    `gen-doc-claims: 回填 ${touched.length} 个文件（${CLAIMS.length} claims，${markerCount} markers）` +
      (touched.length > 0 ? `\n  - ${touched.join("\n  - ")}` : ""),
  );
  if (issues.length > 0) {
    console.error(`gen-doc-claims: ${issues.length} 处无法处理`);
    for (const issue of issues) console.error(`  - ${issue.file}:${issue.line} ${issue.message}`);
    exit(1);
  }
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
