/**
 * src/patent/checker — 推理模式规则（24 条）。
 *
 * 移植自 Mady domains/workflows/patent/reasoning_patterns.go：18 个标准化
 * 推理模式 × CheckRules。推理模式编码复审/无效实务中的规范推理模板，
 * 规则用 PathElements 校验推理路径步骤完整性（每步至少命中其一）。
 */

import type { CheckRule } from "./types.js";
import { LevelMust, LevelQuality, LevelShould } from "./types.js";
import {
  TERM_CAN_USE,
  TERM_CLOSEST_PRIOR_ART,
  TERM_COMMON_KNOWLEDGE,
  TERM_DESIGN_PATENT,
  TERM_DIFF_FEATURES,
  TERM_DISTINGUISHING_FEATURES,
  TERM_ENABLEMENT,
  TERM_EXP_DATA,
  TERM_FILING_DATE,
  TERM_FUNCTIONAL_LIMIT,
  TERM_INTERNET_DISCLOSURE,
  TERM_INVENTIVENESS,
  TERM_MENTAL_ACTIVITY,
  TERM_NATURAL_LAW,
  TERM_NOVELTY,
  TERM_OBVIOUS,
  TERM_OVERALL_VISUAL,
  TERM_PERSON_SKILLED,
  TERM_PRIORITY,
  TERM_PRIORITY_DATE,
  TERM_PRIOR_ART,
  TERM_PRIOR_ART_DOC,
  TERM_PRODUCT_CATEGORY,
  TERM_PROTECTION_SCOPE,
  TERM_SCI_DISCOVERY,
  TERM_TECH_EFFECT,
  TERM_TECH_HINT,
  TERM_TECH_SOLUTION,
  TERM_USE_LIMIT,
  DOMAIN_AMENDMENT,
  DOMAIN_CLAIMS,
  DOMAIN_DESIGN,
  DOMAIN_DISCLOSURE,
  DOMAIN_EXAMINATION,
  DOMAIN_INVENTIVENESS,
  DOMAIN_NOVELTY,
  DIM_CLARITY,
  DIM_SUPPORT,
} from "./constants.js";

/**
 * 推理模式规则（移植 Mady domains/workflows/patent/reasoning_patterns.go，
 * 18 个标准化推理模式 × CheckRules = 24 条确定性规则）。
 * 推理模式编码复审/无效实务中的规范推理模板，规则用 PathElements 校验
 * 推理路径步骤完整性（每步至少命中其一）。
 */
export function reasoningPatternRules(): CheckRule[] {
  return [
    // ---- 创造性（6 模式） ----
    {
      id: "REASON-CREATIVITY-01A",
      name: "单对比文件+公知常识审查",
      description: "区别特征属于公知常识的创造性否定路径：无需额外对比文件",
      level: LevelMust,
      severity: "critical",
      message: "创造性分析未完整论证公知常识路径",
      checkType: "patent_inventiveness",
      domain: DOMAIN_INVENTIVENESS,
      pathElements: [
        ["最接近的现有技术", TERM_CLOSEST_PRIOR_ART],
        [TERM_DISTINGUISHING_FEATURES, TERM_DIFF_FEATURES],
        [TERM_COMMON_KNOWLEDGE, "惯用技术手段", "常规设计", "本领域常规"],
        [TERM_OBVIOUS, "无需创造性劳动", "非显而易见"],
      ],
      fixSuggestion: "按三步法论证：最接近现有技术→区别特征→区别特征属于公知常识→无需创造性劳动",
    },
    {
      id: "REASON-CREATIVITY-01B",
      name: "公知常识证据支撑",
      description: "公知常识主张应提供足以使本领域技术人员信服的论证或证据",
      level: LevelShould,
      severity: "major",
      message: "公知常识的认定缺乏充分论证",
      checkType: "patent_inventiveness",
      requiredElements: [TERM_COMMON_KNOWLEDGE],
      domain: DOMAIN_INVENTIVENESS,
      fixSuggestion: "提供公知常识性证据（教科书/工具书）或充分论述该技术手段的普遍性",
    },
    {
      id: "REASON-CREATIVITY-02",
      name: "多对比文件结合审查",
      description: "多篇对比文件结合时须论证结合动机/技术启示",
      level: LevelMust,
      severity: "critical",
      message: "多对比文件结合缺少组合动机论证",
      checkType: "patent_inventiveness",
      domain: DOMAIN_INVENTIVENESS,
      pathElements: [
        ["最接近的现有技术", TERM_CLOSEST_PRIOR_ART, "对比文件1"],
        [TERM_DISTINGUISHING_FEATURES, TERM_DIFF_FEATURES],
        [TERM_TECH_HINT, "组合动机", "结合动机", "结合启示"],
      ],
      fixSuggestion: "说明本领域技术人员有动机将多篇对比文件结合的技术原因和现有技术教导",
    },
    {
      id: "REASON-CREATIVITY-03",
      name: "技术启示判断审查",
      description: "三步法第三步：技术启示的客观判断",
      level: LevelMust,
      severity: "critical",
      message: "创造性分析未充分论证是否存在技术启示",
      checkType: "patent_inventiveness",
      domain: DOMAIN_INVENTIVENESS,
      pathElements: [
        [TERM_TECH_HINT, "teaching suggestion motivation"],
        [TERM_OBVIOUS, "obvious", "显而易见性"],
        [TERM_PERSON_SKILLED, "所属领域技术人员", "person skilled in the art"],
      ],
      fixSuggestion: "以三步法为基础，重点论证现有技术整体上是否存在使本领域技术人员获得该发明的技术启示",
    },
    {
      id: "REASON-CREATIVITY-04",
      name: "惯用手段与常规选择审查",
      description: "惯用技术手段/常规选择可直接否定创造性",
      level: LevelShould,
      severity: "major",
      message: "惯用技术手段认定缺乏充分论述",
      checkType: "patent_inventiveness",
      domain: DOMAIN_INVENTIVENESS,
      pathElements: [
        ["惯用技术手段", "惯用手段", "常规设计", "本领域常规"],
        ["众所周知", "本领域通用", "common general knowledge"],
      ],
      fixSuggestion: "明确该技术手段在本领域的普遍性和常规性，可引用教科书或工具书佐证",
    },
    {
      id: "REASON-CREATIVITY-05",
      name: "用途限定的影响审查",
      description: "用途特征对创造性判断的影响分析",
      level: LevelShould,
      severity: "major",
      message: "未分析用途特征对创造性的实际影响",
      checkType: "patent_inventiveness",
      domain: DOMAIN_INVENTIVENESS,
      pathElements: [
        ["用途特征", TERM_USE_LIMIT, "use limitation", "用途"],
        ["产品本身", "产品结构", "产品组成", "产品工艺"],
        [TERM_INVENTIVENESS, "非显而易见"],
      ],
      fixSuggestion: "分析用途特征是否隐含了产品的结构/组成/工艺变化，说明其对创造性判断的贡献",
    },
    {
      id: "REASON-CREATIVITY-06",
      name: "预料不到的效果认定审查",
      description: "预料不到的技术效果作为创造性辅助判断因素",
      level: LevelQuality,
      severity: "minor",
      message: "未分析是否存在预料不到的技术效果",
      checkType: "patent_inventiveness",
      domain: DOMAIN_INVENTIVENESS,
      pathElements: [
        ["预料不到", "出乎意料", "surprising", "unexpected"],
        [TERM_TECH_EFFECT, "有益效果", "效果"],
        [TERM_INVENTIVENESS, "创造性的辅助判断"],
      ],
      fixSuggestion: "说明发明产生了哪些本领域技术人员无法合理预期的技术效果及其证据",
    },

    // ---- 新颖性（3 模式） ----
    {
      id: "REASON-NOVELTY-01A",
      name: "现有技术认定审查",
      description: "新颖性判断的单独对比+四相同原则",
      level: LevelMust,
      severity: "critical",
      message: "新颖性分析未遵循单独对比和四相同标准",
      checkType: "patent_novelty",
      domain: DOMAIN_NOVELTY,
      pathElements: [
        [TERM_PRIOR_ART, "prior art"],
        ["单独对比", "单独对比原则", "一一对比"],
        ["技术领域", "技术问题", TERM_TECH_SOLUTION, TERM_TECH_EFFECT],
      ],
      singleComparison: true,
      fixSuggestion: "按四相同标准逐一比对：技术领域/技术问题/技术方案/预期效果",
    },
    {
      id: "REASON-NOVELTY-01B",
      name: "四相同标准审查",
      description: "四相同标准中技术方案和效果的全面比对",
      level: LevelShould,
      severity: "major",
      message: "四相同标准分析不完整",
      checkType: "patent_novelty",
      requiredElements: [TERM_TECH_SOLUTION, TERM_TECH_EFFECT],
      domain: DOMAIN_NOVELTY,
      fixSuggestion: "确保技术方案四要素（领域/问题/方案/效果）均得到分析",
    },
    {
      id: "REASON-NOVELTY-02A",
      name: "公开方式判断审查",
      description: "出版物、使用、互联网三种公开方式的认定",
      level: LevelShould,
      severity: "major",
      message: "未充分分析现有技术的公开方式",
      checkType: "patent_public_access",
      domain: DOMAIN_NOVELTY,
      pathElements: [
        ["公开方式", "公开形式", "公开途径"],
        ["申请日", "公开日", TERM_PRIORITY_DATE],
      ],
      fixSuggestion: "明确认定现有技术的公开方式（出版物/使用/互联网）和公开时间",
    },
    {
      id: "REASON-NOVELTY-02B",
      name: "互联网公开认定审查",
      description: "互联网公开的认定及其公开日的确定",
      level: LevelShould,
      severity: "major",
      message: "互联网公开分析不完整",
      checkType: "patent_public_access",
      requiredElements: [TERM_INTERNET_DISCLOSURE, "网络公开"],
      domain: DOMAIN_NOVELTY,
      fixSuggestion: "确认网页公开日的确定方式及公众能够获知的途径",
    },
    {
      id: "REASON-NOVELTY-03A",
      name: "抵触申请审查",
      description: "抵触申请的构成要件及其仅用于新颖性判断的限制",
      level: LevelMust,
      severity: "critical",
      message: "抵触申请分析不完整或误用于创造性判断",
      checkType: "patent_novelty",
      domain: DOMAIN_NOVELTY,
      pathElements: [
        ["抵触申请", "在先申请在后公开", "conflicting application"],
        [TERM_NOVELTY, "新颖性判断"],
      ],
      fixSuggestion: "确认对比文件是否构成抵触申请，仅用于新颖性判断",
    },
    {
      id: "REASON-NOVELTY-03B",
      name: "优先权审查",
      description: "优先权日的认定及其对现有技术判断的影响",
      level: LevelShould,
      severity: "major",
      message: "未充分核实优先权日及其有效性",
      checkType: "patent_novelty",
      domain: DOMAIN_NOVELTY,
      pathElements: [
        [TERM_PRIORITY, TERM_PRIORITY_DATE, "priority date"],
        ["申请日", TERM_FILING_DATE],
        [TERM_PRIOR_ART, TERM_PRIOR_ART_DOC],
      ],
      fixSuggestion: "核实优先权是否有效，以优先权日作为现有技术判断的时间基准",
    },

    // ---- 权利要求/说明书（5 模式） ----
    {
      id: "REASON-CLAIMS-01",
      name: "不清楚认定审查",
      description: "权利要求保护范围的清楚性判断",
      level: LevelShould,
      severity: "major",
      message: "权利要求不清楚性分析不完整",
      checkType: "patent_claim_analysis",
      domain: DOMAIN_CLAIMS,
      dimensions: [DIM_CLARITY],
      pathElements: [
        ["清楚", "清晰", "明确", "简要"],
        ["权利要求", TERM_PROTECTION_SCOPE],
        ["含义不确定", "术语含义不明"],
      ],
      fixSuggestion: "逐一审查权利要求每个术语的含义是否明确，删除含义不确定的表述",
    },
    {
      id: "REASON-CLAIMS-02",
      name: "不支持认定审查",
      description: "权利要求是否得到说明书支持",
      level: LevelShould,
      severity: "major",
      message: "权利要求未充分分析是否得到说明书支持",
      checkType: "patent_claim_analysis",
      domain: DOMAIN_CLAIMS,
      dimensions: [DIM_SUPPORT],
      pathElements: [
        ["以说明书为依据", "说明书支持", "支持"],
        ["合理概括", "概括范围"],
        ["权利要求", TERM_PROTECTION_SCOPE],
      ],
      fixSuggestion: "比对权利要求与说明书的具体实施方式和实施例，确认概括范围是否合理",
    },
    {
      id: "REASON-CLAIMS-03",
      name: "功能性限定审查",
      description: "功能性限定的解释范围与审查规则",
      level: LevelShould,
      severity: "major",
      message: "未充分分析功能性限定的解释范围",
      checkType: "patent_claim_analysis",
      domain: DOMAIN_CLAIMS,
      pathElements: [
        [TERM_FUNCTIONAL_LIMIT, "功能限定", "功能性特征", "functional limitation"],
        ["具体实施方式", "实施例"],
        [TERM_PROTECTION_SCOPE, "解释范围"],
      ],
      fixSuggestion: "确认说明书记载了实现该功能的具体实施方式，以此限定功能性特征的保护范围",
    },
    {
      id: "REASON-CLAIMS-04",
      name: "充分公开认定审查",
      description: "能够实现标准的审查逻辑",
      level: LevelShould,
      severity: "major",
      message: "充分公开分析未完整覆盖能够实现标准的审查维度",
      checkType: "patent_disclosure",
      domain: DOMAIN_DISCLOSURE,
      pathElements: [
        ["充分公开", "公开充分", TERM_ENABLEMENT],
        ["能够实现", "可实施", "能够制造", TERM_CAN_USE],
        [TERM_TECH_SOLUTION, TERM_TECH_EFFECT],
      ],
      fixSuggestion: "从技术方案完整性、可实施性、技术效果三个维度论证充分公开",
    },
    {
      id: "REASON-CLAIMS-05",
      name: "实验数据要求审查",
      description: "医药化学领域实验数据的满足度判断",
      level: LevelShould,
      severity: "major",
      message: "实验数据满足度分析不充分",
      checkType: "patent_disclosure",
      domain: DOMAIN_DISCLOSURE,
      pathElements: [
        [TERM_EXP_DATA, "实验例", "试验数据"],
        ["能够实现", "证实", "证明", "验证"],
        ["充分公开", "公开充分"],
      ],
      fixSuggestion: "审查实验数据是否足以证明技术方案能够实现所述用途/效果，数据是否可重现",
    },

    // ---- 其他（4 模式） ----
    {
      id: "REASON-OTHER-01A",
      name: "保护客体-技术方案认定审查",
      description: "第2条可专利主题判断",
      level: LevelMust,
      severity: "critical",
      message: "保护客体分析不完整，未充分论证是否构成技术方案",
      checkType: "patent_subject_matter",
      domain: DOMAIN_EXAMINATION,
      pathElements: [
        [TERM_TECH_SOLUTION, "technical solution"],
        [TERM_NATURAL_LAW, "自然法则"],
        ["保护客体", "可专利主题", "授权客体", "patentable subject matter"],
      ],
      fixSuggestion: "论证是否构成技术方案（利用自然规律、解决技术问题、产生技术效果），并排除非可专利客体",
    },
    {
      id: "REASON-OTHER-01B",
      name: "非可专利客体排除审查",
      description: "排除科学发现/智力活动规则/疾病诊断治疗方法的论证",
      level: LevelShould,
      severity: "major",
      message: "未充分分析是否属于非可专利客体",
      checkType: "patent_subject_matter",
      requiredElements: [TERM_SCI_DISCOVERY, TERM_MENTAL_ACTIVITY, "疾病诊断方法"],
      domain: DOMAIN_EXAMINATION,
      fixSuggestion: "逐项排除：科学发现、智力活动规则、疾病诊断治疗方法、原子核变换方法",
    },
    {
      id: "REASON-OTHER-02A",
      name: "修改超范围审查",
      description: "修改内容是否超出原申请文件记载范围",
      level: LevelMust,
      severity: "critical",
      message: "修改超范围分析不完整",
      checkType: "patent_amendment_scope",
      domain: DOMAIN_AMENDMENT,
      pathElements: [
        ["修改超范围", "超范围", "超出原范围", "超范围修改", "amendment beyond scope"],
        ["直接且毫无疑义", "直接毫无疑义", "原申请文件"],
        ["原说明书", "原权利要求", "原始公开"],
      ],
      fixSuggestion: "确认修改内容是否能够从原说明书和权利要求书记载的范围中直接且毫无疑义地确定",
    },
    {
      id: "REASON-OTHER-02B",
      name: "优先权程序审查",
      description: "优先权转让及主张的程序合规性",
      level: LevelShould,
      severity: "major",
      message: "优先权程序审查不完整",
      checkType: "patent_amendment_scope",
      domain: DOMAIN_AMENDMENT,
      pathElements: [
        [TERM_PRIORITY, TERM_PRIORITY_DATE, "优先权转让"],
        ["申请日", TERM_FILING_DATE],
        ["转让", "transfer", "assign"],
      ],
      fixSuggestion: "核实优先权转让是否在申请日前完成，优先权主张是否符合程序要求",
    },
    {
      id: "REASON-OTHER-03",
      name: "实用性-积极效果与产业应用审查",
      description: "第22条第4款实用性判断",
      level: LevelShould,
      severity: "major",
      message: "实用性分析不完整",
      checkType: "patent_subject_matter",
      domain: DOMAIN_EXAMINATION,
      pathElements: [
        ["实用性", "工业实用性", "产业应用", "industrial applicability"],
        ["能够制造", TERM_CAN_USE],
        ["积极效果", "有益效果", "positive effect"],
      ],
      fixSuggestion: "论证本领域技术人员能够在产业上制造或使用该发明，并产生积极效果",
    },
    {
      id: "REASON-OTHER-04",
      name: "整体视觉效果对比审查",
      description: "外观设计四步推理结构：产品种类→整体视觉→相同/近似判断",
      level: LevelShould,
      severity: "major",
      message: "外观设计对比分析不完整，缺少整体视觉效果判断",
      checkType: "patent_design_comparison",
      domain: DOMAIN_DESIGN,
      pathElements: [
        [TERM_DESIGN_PATENT, "工业设计", "design", "industrial design"],
        [TERM_OVERALL_VISUAL, "视觉效果", "整体外观", "整体视觉", "overall visual effect"],
        [TERM_PRODUCT_CATEGORY, "产品类别", "同类产品", "相近种类"],
        ["相同", "近似", "实质相同"],
      ],
      fixSuggestion: "按四步结构分析：确定产品种类→明确整体视觉效果→对比整体视觉效果→判断相同/近似",
    },
  ];
}
