export {
  GatewayBrowserClient,
  readLocalGatewayToken,
  type GatewayBrowserClientOptions,
  type GatewayBrowserStream,
  type WebSocketLike,
} from "./GatewayBrowserClient.js";
export {
  SATI_GATEWAY_PROTOCOL_VERSION_WEB,
  type WebActiveTurnSnapshot,
  type WebActiveTurnSnapshotInput,
  type WebAlwaysOnApplyCycleInput,
  type WebAlwaysOnApplyCycleResult,
  type WebAlwaysOnArchiveCycleInput,
  type WebAlwaysOnArchiveCycleResult,
  type WebAlwaysOnCycle,
  type WebAlwaysOnListCyclesInput,
  type WebAlwaysOnListCyclesResult,
  type WebAlwaysOnListPlansInput,
  type WebAlwaysOnListPlansResult,
  type WebAlwaysOnReadReportInput,
  type WebAlwaysOnReadReportResult,
  type WebAlwaysOnWebPlan,
  type WebChannelAttachment,
  type WebElicitationAnswer,
  type WebElicitationQuestion,
  type WebEventFrame,
  type WebGatewayChannelKey,
  type WebGatewayEvent,
  type WebGatewayFrame,
  type WebGatewayMethod,
  type WebGatewayMode,
  type WebAgentRunMode,
  type WebHelloOk,
  type WebListProjectsResult,
  type WebListSessionsInput,
  type WebListSessionsResult,
  type WebPermissionDecision,
  type WebProjectSummary,
  type WebReadSessionMessagesInput,
  type WebReadSessionMessagesResult,
  type WebReadSubagentMessagesInput,
  type WebReadSubagentMessagesResult,
  type WebRequestFrame,
  type WebResponseFrame,
  type WebSessionInfo,
  type WebSubmitTurnInput,
} from "./protocol.js";
export {
  isVisibleFailureStatusDetail,
  limitToolResultPreview,
  mapGatewayEventToFrames,
  normalizeToolDisplayName,
  normalizeToolErrorCode,
  tryParseJson,
  VISIBLE_FAILURE_AGENT_STATUS_EVENTS,
  type GatewayEventFrame,
} from "./eventMapping.js";
export {
  applyWebGatewayEvent,
  createWebMessageReducerState,
  type WebMessage,
  type WebMessageKind,
  type WebMessageReducerOptions,
  type WebMessageReducerState,
  type WebMessageRole,
} from "./webMessage.js";
