/**
 * src/patent — 专利域模块 barrel。
 *
 * - output-gate / quality-gate：输出门禁（HITL 审批挂起 + 质量门禁）——外部消费者
 *   统一从本 barrel 导入，勿深路径直入内部文件；声明式规则镜像：
 *   rules/patent/compliance.yaml 与本模块的关键词表互为镜像（改词需两处同步，注释互指）。
 * - workflow：声明式工作流执行器（内置 patentNoveltyManifest 五阶段新颖性分析）
 * - flexible-plan：灵活计划层（阶段级生命周期管理：增删改阶段/逐阶段确认/
 *   回退重做/法条判定挂接，toManifest 交 runWorkflow 执行）
 * - plantask：人机协作计划状态机（HITL 闭环：planning→approval→executing→feedback→replanning）
 * - worker-contract：Worker 契约注册表与输出校验（defaultPatentWorkers 内置目录）
 */

export {
  PatentOutputGate,
  extractMessageText,
  type PatentOutputGateOptions,
  type PendingPatentMessage,
  type ProcessedMessageResult,
} from "./output-gate.js";
export { ABSOLUTE_PHRASES } from "./quality-gate.js";
export {
  type ApprovalRecord,
  type ApprovalVerdict,
  type ApprovalStore,
  InMemoryApprovalStore,
  createApprovalRecord,
} from "./approval.js";

export {
  CASE_ROOT_REL,
  CASE_OUTPUTS_REL,
  CASE_WORKFLOW_RUNS_REL,
  CASE_INVENTIVENESS_FEEDBACK_FILE,
  caseOutputsDir,
  caseWorkflowRunsDir,
  caseInventivenessFeedbackPath,
} from "./paths.js";

export {
  appendInventivenessFeedback,
  loadInventivenessFeedback,
  summarizeInventivenessFeedback,
  type InventivenessFeedbackRecord,
} from "./feedback/inventiveness-feedback.js";

export {
  type WorkflowStage,
  type WorkflowContext,
  type WorkflowManifest,
  type WorkflowRunResult,
  type WorkflowRunOptions,
  type WorkflowRunStore,
  type WorkflowInterrupt,
  type ManifestCheckpoint,
  type ManifestCheckpointStage,
  type ManifestCheckpointStore,
  WorkflowError,
  validateWorkflowManifest,
  runWorkflow,
  JsonFileManifestCheckpointStore,
  restoreFromCheckpoint,
  stageToCheckpointStage,
  patentNoveltyManifest,
  patentDisclosureManifest,
  patentInventivenessManifest,
  patentPatentabilityManifest,
  patentOaResponseManifest,
  patentInvalidationManifest,
  patentInfringementManifest,
  patentDraftingManifest,
  builtinPatentManifests,
  type BuiltinPatentManifest,
} from "./workflow.js";

export {
  manifestToFlowGraph,
  validateWorkflowManifestDag,
  workflowManifestToMermaid,
} from "./workflow-dag.js";

export {
  // 契约
  type GraphState,
  type StateDelta,
  type GraphNodeContext,
  type GraphNode,
  type EdgeRouter,
  type NodePolicy,
  type Reducer,
  type NodeResult,
  type NodeOutcome,
  type RunOptions,
  type GraphRunResult,
  type DegradationMark,
  type DegradationReason,
  type GraphCheckpoint,
  type CheckpointStore,
  GRAPH_END,
  GraphInterruptError,
  isGraphInterruptError,
  GraphEngineError,
  // 状态工具
  cloneState,
  getStateString,
  getStateArray,
  getStateObject,
  // 降级标记
  DEGRADATION_SUFFIX,
  markDegraded,
  isDegraded,
  getDegradationMark,
  degradationSummary,
  // 合并
  mergeWithSchema,
  GraphMergeError,
  type MergeSchema,
  // 节点策略
  runNodeWithPolicy,
  // 引擎
  GraphBuilder,
  CompiledGraph,
  type CompiledGraphDef,
  type ResumePoint,
  // 检查点
  InMemoryCheckpointStore,
  JsonFileCheckpointStore,
  runGraphWithCheckpoints,
  grantApproval,
  type CheckpointedRunOptions,
  type CheckpointedRunResult,
  // 适配层
  runStageHandler,
  manifestToGraph,
  type ManifestToGraphDeps,
  // 三性领域子图
  buildNoveltyGraph,
  extractNumericRanges,
  type BuildNoveltyGraphOptions,
  buildInventivenessGraph,
  extractInventivenessResult,
  type BuildInventivenessGraphOptions,
  buildEnablementGraph,
  extractEnablementResult,
  detectTechnicalDomain,
  type BuildEnablementGraphOptions,
  handlerNode,
  llmNode,
  ruleGateNode,
  collectStateText,
  resolveInput,
  type LlmNodeOptions,
  type RuleGateState,
  // 三性领域子图注册表
  DOMAIN_GRAPHS,
  DOMAIN_INPUT_DECLARATIONS,
  type DomainGraphName,
} from "./graph/index.js";

export {
  // 评估框架
  Evaluator,
  DEFAULT_METRICS,
  extractKeywords,
  keywordRecall,
  citationCompleteness,
  ruleGatePass,
  jaccardSimilarity,
  llmJudge,
  parseJudgeScore,
  createGraphRunner,
  defaultDomainGraphMap,
  evaluateSingleText,
  type EvalCase,
  type EvalOutcome,
  type CaseRunner,
  type BatchReport,
  type EvaluatorOptions,
  type LlmJudgeOptions,
  type LlmJudgeClient,
  type GraphRunnerOptions,
} from "./evaluate/index.js";

export {
  FlexiblePlanError,
  createFlexiblePlan,
  addStage,
  removeStage,
  reorderStages,
  confirmStage,
  rollbackStage,
  attachArticleJudgment,
  toManifest,
  toCompiledGraph,
  complete,
  abandon,
  toJSON,
  fromJSON,
  type FlexibleStageStatus,
  type FlexibleStage,
  type FlexiblePlanStatus,
  type FlexiblePlanState,
  type CreateFlexiblePlanOptions,
} from "./flexible-plan.js";
export {
  type FlexiblePlanStore,
  JsonFileFlexiblePlanStore,
} from "./flexible-plan-store.js";

export {
  InMemoryWorkflowRunStore,
  JsonFileWorkflowRunStore,
} from "./workflow-store.js";

export {
  type EvidenceSpan,
  type EvidenceDirection,
  type EvidenceConflict,
  createSpan,
  isLocatable,
  Ledger,
  contentHash,
  receiptFromToolExecution,
  ClaimBinding,
  ConflictDetector,
  EvidenceExtension,
  EvidenceEngine,
  inferEvidenceType,
  evaluateFourElements,
  STANDARD_PREPONDERANCE,
  STANDARD_CLEAR_CONVINCING,
  loadEvidenceRulesEngine,
  platformCredibility,
  credibilityToScore,
  platformCategory,
  evaluatePublicIntent,
  parseDateFlexible,
  isPreciseDate,
  isMonthOnlyDate,
  inferredMonthEnd,
  extractDateFromText,
  isBeforeFilingDate,
  determinePublicationDate,
  extractWaybackMachineDate,
  cleanEvidenceURI,
} from "./evidence/index.js";
export type {
  EvidenceJudgment,
  DimensionJudgment,
  TypeSpecificJudgment,
  BurdenDetermination,
  ProofStandardResult,
  EvidenceRule,
  EvidenceRuleSet,
  EvidenceType,
  CredibilityLevel,
  DateDetermination,
  FourElementsResult,
  EvidenceExternalInputs,
  EvidenceJudgmentEngine,
  RuleApplication,
} from "./evidence/types.js";

export {
  analyzeSlop,
  detectStructureIssues,
  formatSlopAnalysis,
  runChecklist,
  runeSlice,
  scoreDocument,
  type SlopAnalysis,
  type SlopChange,
  type SlopGroup,
  type SlopScore,
  type StructureIssue,
  type StructureIssueType,
  type ChecklistItem,
} from "./slop-engine.js";

export {
  FactBlackboard,
  ConfirmedRuleSet,
  SyllogismBuilder,
  SyllogismError,
  ruleAssertion,
  assertChain,
  type FactEntry,
  type FactCategory,
  type RuleConstraint,
  type Requirement,
  type RuleConfirmation,
  type ConfirmedRuleEntry,
  type ArticleJudgment,
  type ReasoningChain,
  type ReasoningChainNode,
  type FactBlackboardOptions,
  type Syllogism,
  type Premise,
  type PremiseSource,
} from "./reasoning/index.js";

export {
  type Atom,
  type AtomCategory,
  AtomRegistry,
  AtomRegistryError,
  globalAtomRegistry,
  RegisterAtom,
  LookupAtom,
  ListAtoms,
  ListAtomsByCategory,
  type PipelineState,
  type StageProvider,
  type StageExecuteInput,
  type StageHandler,
  StageError,
  InterruptStageError,
  isInterruptStageError,
  StageHandlerRegistry,
  globalStageHandlerRegistry,
  RegisterStageHandler,
  LookupStageHandler,
  registerBuiltinAtoms,
  searchAtom,
  SearchHandler,
  extractAtom,
  ExtractHandler,
  compareAtom,
  CompareHandler,
  reasoningAtom,
  ReasoningHandler,
  approvalGateAtom,
  ApprovalGateHandler,
  APPROVAL_GRANTED_KEY,
  APPROVAL_GRANTED_OUTPUT,
  isApprovalGateHandler,
  groundednessAtom,
  GroundednessHandler,
  GROUNDEDNESS_THRESHOLD,
  keywordsAtom,
  KeywordsHandler,
  noveltyAtom,
  NoveltyHandler,
  evidenceCoverage,
  mergeAtom,
  MergeHandler,
  draftClaimsAtom,
  DraftClaimsHandler,
  draftSpecAtom,
  DraftSpecHandler,
  validateDraftSpec,
  qualityGateAtom,
  QualityGateHandler,
  slopGateAtom,
  SlopGateHandler,
  type SpecViolation,
  type PFETriple,
} from "./atoms/index.js";

export {
  checkSearchQuality,
  MIN_DOCS,
  MIN_RELATEDNESS_MARKS,
  MIN_FULLTEXT_MARKS,
  type SearchQualityResult,
} from "./quality/index.js";

export {
  type PlanTaskState,
  type PlanTask,
  TRANSITIONS,
  PlanTaskStateMachine,
  PlanTaskStateError,
  PlanTaskSemanticError,
  type PlanTaskTransitionContext,
  syncPlanToTasks,
  replanTasks,
} from "./plantask.js";

export {
  WorkerRegistry,
  WorkerMonitor,
  validateWorkerOutput,
  defaultPatentWorkers,
  WORKER_ROLE_MAP,
  ROLE_WORKER_TIERS,
  workerAllowedForRole,
} from "./worker-contract.js";

export {
  RuleEngine,
  aggregate,
  formatRuleResults,
  matchKeyword,
  matchKeywordsAll,
  matchKeywordsAny,
  defaultPatentRules,
  noveltyRules,
  inventivenessRules,
  disclosureRules,
  infringementRules,
  invalidationRules,
  reexaminationRules,
  specRules,
  designRules,
  priorityRules,
  publicAccessRules,
  subjectMatterRules,
  type CheckRule,
  type CheckType,
  type RuleCheckResult,
  type RuleEngineOptions,
  type RuleLevel,
  type Severity,
  type Verdict,
} from "./checker/index.js";

export {
  checkAtomic,
  type AtomicCheckResult,
  type AtomicChecks,
} from "./problem/index.js";

export {
  CHEMICAL_KINDS,
  CHEMISTRY_INDEX_VERSION,
  DEFAULT_CHEMISTRY_INDEX_RELATIVE_PATH,
  DEFAULT_CHEMISTRY_PROVIDER,
  DEFAULT_CHEMISTRY_MODEL,
  CHEMISTRY_MIN_CONFIDENCE,
  analyzeChemicalImage,
  analyzeChemicalName,
  analyzeChemicalText,
  recognizeChemicalStructure,
  extractFormulaCandidates,
  extractSmilesCandidates,
  extractChemicalCandidates,
  formulaFromInChI,
  countElementsFromSmiles,
  isPlausibleSmilesSyntax,
  isRdkitAvailable,
  loadRdkitModule,
  loadChemistryIndex,
  saveChemistryIndex,
  upsertChemistryIndex,
  validateSmiles,
  type ChemicalImageInput,
  type ChemicalKind,
  type ChemicalSmilesCandidate,
  type ChemicalStructureResult,
  type ChemistryAnalyzerOptions,
  type ChemistryIndexEntry,
  type ChemistryIndexFile,
  type ChemistryModelClient,
  type ChemistryPhase,
  type LoadChemistryIndexResult,
  type SmilesValidationResult,
} from "./chemistry/index.js";

export {
  FIGURE_TYPES,
  FIGURE_TYPE_NAMES,
  FIGURE_COMPONENT_KINDS,
  FIGURE_CONNECTION_KINDS,
  ELECTRICAL_CATEGORIES,
  DEFAULT_FIGURE_PROVIDER,
  DEFAULT_FIGURE_MODEL,
  analyzePatentFigure,
  analyzeElectricalFigure,
  validateElectricalAnalysis,
  extractClaimRefs,
  loadElectricalSymbols,
  querySymbolByRefPrefix,
  querySymbolById,
  parseRefNumber,
  formatSymbolsAsContext,
  loadFigureImage,
  loadFigureIndex,
  saveFigureIndex,
  upsertFigureIndex,
  retrieveFigures,
  FIGURE_INDEX_VERSION,
  DEFAULT_FIGURE_INDEX_RELATIVE_PATH,
  normalizeFigureType,
  normalizeComponentKind,
  normalizeConnectionKind,
  normalizeElectricalCategory,
  type FigureType,
  type FigureComponentKind,
  type FigureConnectionKind,
  type ElectricalCategory,
  type FigureComponent,
  type FigureConnection,
  type ElectricalComponent,
  type ElectricalNet,
  type ElectricalAnalysis,
  type FigureAnalysisResult,
  type FigureAnalyzerOptions,
  type FigureModelClient,
  type FigureAnalysisPhase,
  type AnalyzePatentFigureInput,
  type AnalyzeElectricalInput,
  type AnalyzeElectricalOptions,
  type ElectricalValidationResult,
  type ElectricalSymbolCategory,
  type ElectricalSymbolEntry,
  type ElectricalSymbolIndex,
  type FigureIndexEntry,
  type FigureIndexFile,
  type FigureRetrieveMethod,
  type FigureRetrieveHit,
  type FigureRetrieveResult,
  type FigureRetrieveOptions,
} from "./figure/index.js";
export * from "./claim-chart/index.js";
export * from "./document/index.js";
